export const GET_OFFERS = 'GET_OFFERS';
export const GET_CURRENT_OFFER = 'GET_CURRENT_OFFER';
export const UPDATE_CURRENT_OFFER = 'UPDATE_CURRENT_OFFER';
export const POST_OFFER_SUCCESS = 'POST_OFFER_SUCCESS';
export const POST_OFFER_ERROR = 'POST_OFFER_ERROR';
export const EDIT_POST_OFFER_SUCCESS = 'EDIT_POST_OFFER_SUCCESS';
export const EDIT_POST_OFFER_ERROR = 'EDIT_POST_OFFER_ERROR';